# Load Antigen
source ~/.antigen.zsh
# Load Antigen configurations
antigen init ~/.antigenrc

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# theme
POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(ram root_indicator background_jobs)
POWERLEVEL9K_PROMPT_ON_NEWLINE=false

source $ZSH/oh-my-zsh.sh

# alias
alias lk="colorls --sd -A"
alias l="colorls"
alias c="clear"
alias e="exit"
alias logout="loginctl terminate-user"

# z plugin 
. ~/.z.sh

# gopath
export GOPATH=$HOME/go
