# Path exports
export ZSH="$HOME/.oh-my-zsh"
export GOPATH=$HOME/go

# File Loading
source ~/.antigen.zsh
antigen init ~/.antigenrc

source $ZSH/oh-my-zsh.sh

# Alias 
alias ls="colorls"
alias c="clear"
alias e="exit"
# git alias
alias dif="git diff"
alias sta="git status"
alias com="git commit -m"
alias add="git add"

alias logout="loginctl terminate-user"

# Config
# theme
POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(ram root_indicator background_jobs)
POWERLEVEL9K_PROMPT_ON_NEWLINE=false

# z plugin 
. ~/.z.sh

