# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path exports
export ZSH="$HOME/.oh-my-zsh"
export GOPATH=$HOME/go

source $ZSH/oh-my-zsh.sh

# File Loading
source ~/.antigen.zsh
antigen init ~/.antigenrc

# Alias 
alias ls="colorls"
alias c="clear"
alias e="exit"
alias vim="nvim"
# git alias
alias dif="git diff"
alias sta="git status"
alias com="git commit -m"
alias add="git add"
alias pus="git push origin master"

# z plugin 
. ~/.z.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
